apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy-distributor
  labels:
    app: alloy-distributor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alloy-distributor
  template:
    metadata:
      labels:
        app: alloy-distributor
    spec:
      containers:
      - name: alloy-distributor
        image: your-registry/alloy-distributor:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3101
        readinessProbe:
          httpGet:
            path: /ready
            port: 3101
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /ready
            port: 3101
          periodSeconds: 10
        env:
        - name: KAFKA_BROKERS
          value: "kafka1:9092,kafka2:9092,kafka3:9092"
        - name: KAFKA_TOPIC
          value: "alloy_raw_logs"
        - name: KAFKA_REQUIRED_ACKS
          value: "1"
        - name: KAFKA_BALANCER
          value: "sticky"
        - name: KAFKA_WRITE_TIMEOUT
          value: "10s"
        - name: RATE_LIMIT_ENABLED
          value: "true"
        - name: RATE_LIMIT_GLOBAL_RPS
          value: "2000"
        - name: RATE_LIMIT_PER_TENANT_RPS
          value: "500"
        - name: HEALTH_ERROR_RATE_THRESHOLD
          value: "0.05"
        - name: HEALTH_CONSECUTIVE_ERROR_THRESHOLD
          value: "5"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 512Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alloy-distributor-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: alloy-distributor