apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-producer-config
  namespace: project-logging
data:
  config.yaml: |
    kafka_brokers:
      - kafka-cluster-kafka-brokers.project-logging.svc.cluster.local:9094
    kafka_topic: topic-logs
    kafka_required_acks: 1
    kafka_balancer: sticky
    kafka_write_timeout: 10s

    # Kafka writer batching (controls producer flush behavior)
    kafka_batch_timeout: 200ms   # flush interval; lower => lower latency, higher => better throughput
    kafka_batch_size: 100        # max messages per batch; lower => lower latency, higher => larger batches
    kafka_batch_bytes: 200000    # max bytes per batch; safeguard to avoid too-large requests

    # Security (optional)
    kafka_sasl_enabled: true
    kafka_sasl_mechanism: scram-sha-512
    kafka_sasl_username: loki-user
    # kafka_sasl_password: ""    # prefer using secret -> env KAFKA_SASL_PASSWORD
    kafka_tls_enabled: false
    kafka_tls_insecure_skip_verify: false
    # kafka_tls_ca_file: /etc/ssl/certs/ca.pem

    # Startup probe
    kafka_probe_enabled: true
    kafka_probe_required: true
    kafka_probe_timeout: 5s
    kafka_probe_write: true

    max_body_bytes: 5242880
    allow_empty_tenant: false
    default_tenant: anonymous
    metrics_enable_tenant_label: false

    health_error_rate_threshold: 0.05
    health_consecutive_error_threshold: 5
    health_eval_period: 30s
    sla_gauge_enable: true

    rate_limit_enabled: true
    rate_limit_global_rps: 2000
    rate_limit_global_burst: 4000
    rate_limit_per_tenant_rps: 500
    rate_limit_per_tenant_burst: 1000

    log_level: info
    quiet: false
    port: "3101"