apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-producer-config
  namespace: logging
data:
  config.yaml: |
    kafka_brokers:
      - kafka-raft.brokers.svc.cluster.local:9092
    kafka_topic: logs_raw_v1
    kafka_required_acks: 1
    kafka_balancer: sticky
    kafka_write_timeout: 10s

    max_body_bytes: 5242880
    allow_empty_tenant: false
    default_tenant: anonymous
    metrics_enable_tenant_label: false

    health_error_rate_threshold: 0.05
    health_consecutive_error_threshold: 5
    health_eval_period: 30s
    sla_gauge_enable: true

    rate_limit_enabled: true
    rate_limit_global_rps: 2000
    rate_limit_global_burst: 4000
    rate_limit_per_tenant_rps: 500
    rate_limit_per_tenant_burst: 1000

    log_level: info
    quiet: false
    port: "3101"