apiVersion: batch/v1
kind: Job
metadata:
  name: loki-producer-canary-rps-2000-200-v6-debug
  namespace: project-logging
  labels:
    app: loki-producer-canary
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: loki-producer-canary
    spec:
      restartPolicy: Never
      containers:
      - name: canary
        image: dockerdarkhan/loki-producer:v1.4.2
        imagePullPolicy: IfNotPresent
        command: ["/bin/pulse-loki-canary"]
        args:
          - "-url=http://loki-producer.project-logging.svc:3101/loki/api/v1/push"
          - "-tenant=canary"
          - "-tenants=5"
          - "-tenant-prefix=canary"
          - "-rps=2000"
          - "-concurrency=200"
          - "-streams=1"
          - "-lines=10"
          - "-payload-bytes=128"
          - "-gzip=false"
          - "-log-level=debug"
          - "-duration=1m"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 8
            memory: 8Gi
        env:
        - name: CANARY_LOG_LEVEL
          value: debug
