limits:
  reject_old_samples: true
  reject_old_samples_max_age: 168h         # 7 дней
  creation_grace_period: 10m
  max_line_size: 262144                    # 256 KiB
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30
  max_line_size_truncate: true
  max_line_size_truncate_identifier: "…trunc"
